name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile
        run: javac -d out src/*.java test/*.java

      - name: Run tests
        run: |
          mkdir -p out/test-results
          java -cp out org.junit.platform.console.ConsoleLauncher \
            --class-path out \
            --scan-classpath \
            --details tree
